### ISSUE TITLE
Add a readable description for budget_filter.projects in library doc

### ISSUE THREAD

**Issue by theoohoho** [googleapis/python-billingbudgets#130]
Hi, I think the description of `projects` attribute is unclear in `google.cloud.billing.budgets_v1.types.Budget.budget_filter`. 

Because library doc only show  `projects/{project}`, and it's difficult for me to know what the meaning of `project`. (I need to guess the `project` represent **Project ID** or **Project Number**)

Especially, there're 2 example that I test for create budget. One is **Project ID** as `project` of value format e.g., `{projects/projectID}`, and pass in `projects` attribute of `google.cloud.billing.budgets_v1.types.Budget.budget_filter` to create budget, another is **Project Number** e.g., `{projects/projectNumber}`. But the value of `Budget.budget_filter.projects` in the both example response are **Project Number** instead of **Project ID**.

Other method like `list_budget()` and `get_budget()` also respond **Project Number** in `Budget.budget_filter.projects`.

In my opinion, it would be helpful if the library doc can described more clearly for `Budget.budget_filter.projects`.

**Comment by busunkim96** [comment]
Hi @theoohoho,

The API should be able to accept both project ID and project number in requests, but will always return the project number as that is considered canonical.

https://google.aip.dev/cloud/2510#google-apis

> Externally-facing Google APIs should accept both project IDs and project numbers for incoming API requests.
> 
> However, the project number is the canonical identifier, and therefore APIs must use project numbers in responses, regardless of whether they were sent a project ID or a project number.
> 
> There are two exceptions to this rule:
> 
> * Error responses must return the originally-provided value without modification. Error responses must not perform any translation between project IDs and project numbers.
> * If a service receives a resource name for a resource that the service does not own, it should not perform any translation between project IDs and project numbers for those resource names.

**Comment by parthea** [comment]
I'm going to close this issue as a response was provided in https://github.com/googleapis/python-billingbudgets/issues/130#issuecomment-908439627
